# Generated by Django 5.1.4 on 2025-01-02 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options_alter_task_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
