# Generated by Django 5.1.4 on 2025-01-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
